unit TestMVCBrModel;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  DUnitX.TestFramework, System.Classes,
  System.Generics.collections, MVCBr.Interf,
  MVCBr.Controller, System.JSON,
  DataModuleMock, MVCBr.Model, MVCBr.ModuleModel, System.SysUtils,
  MVCBr.Observable;

type
  // Test methods for class TModelFactory

  [TestFixture]
  TModelFactoryMock = class(TModelFactory)
  private
    FRefCount: Integer;
    function GetStubInt: Integer;
    function Update: IModel; override;

  end;

  TestTModelFactory = class
  private

    FModelFactory: TModelFactoryMock;

  Type
    TTesteController = class(TControllerFactory)
    end;
  protected
    FController: IController;
  public

    [Setup]
    procedure SetUp;
    [TearDown]
    procedure TearDown;
  public
    [Test]
    procedure TestGetController;
    [Test]
    procedure TestGetOwned;
    [Test]
    procedure TestController;
    [Test]
    procedure TestThis;
    [Test]
    procedure TestGetID;
    [Test]
    procedure TestID;
    [Test]
    procedure TestUpdate;
    [Test]
    procedure TestAfterInit;

    [Test]
    procedure TestRegisterObserver;
    [Test]
    procedure TestUnRegisterObserverNamed;
    [Test]
    procedure TestUnRegisterObserverNamedOnly;
    [Test]
    procedure TesteObserver;
    Procedure TestCreateLazyModel;
    [Test]
    procedure TestFreeInstanceLazyModel;

  end;

  { TModuleFactoryMock = class(TModuleFactory)
    end;
  }
  TestTModuleModelFactory = class
  private

  [unsafe]
    FModelFactory: IModelAdapter<TDataModuleMockTester>;

  Type
    TTesteController = class(TControllerFactory)
    end;
  public
    [Setup]
    procedure SetUp;
    [TearDown]
    procedure TearDown;

  protected
    [unsafe]
    FController: IController;
  public
    [Test]
    procedure TestGetController;
    [Test]
    procedure TestLazyLoad;
  end;

implementation

procedure TestTModelFactory.SetUp;
begin
  FController := TTesteController.Create;
  FModelFactory := TModelFactoryMock.Create;
  FController.add(FModelFactory);
end;

procedure TestTModelFactory.TearDown;
begin
  FModelFactory := nil;
  FController.release;
  FController := nil;
end;

procedure TestTModelFactory.TestGetController;
var
  ReturnValue: IController;
begin
  ReturnValue := FModelFactory.GetController;
  Assert.IsNotNull(ReturnValue, 'Nao retornou');
  Assert.IsTrue(TMVCBr.IsSame(IController, TMVCBr.GetGuid(ReturnValue)));
end;

procedure TestTModelFactory.TestGetOwned;
var
  ReturnValue: TComponent;
begin
  ReturnValue := FModelFactory.GetOwner;
  Assert.IsNotNull(ReturnValue, 'Nao retornou');
end;

procedure TestTModelFactory.TestController;
var
  ReturnValue: IModel;
  AController: IController;
begin
  AController := FController;
  ReturnValue := FModelFactory.Controller(AController);
  Assert.IsNotNull(ReturnValue, 'Nao retornou');
  Assert.AreSame(FController, FModelFactory.GetController,
    'Controller should be set after Controller() call');
end;


type
    TObjectComum = class(TObject)
      public
         FCount:integer;
         procedure Execute(AValue:Integer);
    end;

procedure TestTModelFactory.TestCreateLazyModel;
var LModel:IModelAdapter<TObjectComum>;
    LController:IController;
begin

    LModel := TModelAdapterFactory<TObjectComum>.new(LController);
    LModel.Instance.Execute(10);
    Assert.IsTrue(LModel.Instance.FCount=10,'N�o atribuiu valor');
    LModel := nil;


end;

procedure TestTModelFactory.TesteObserver;
var
  ref: Integer;
begin
  TMVCBr.RegisterObserver('x', FModelFactory);
  ref := FModelFactory.GetStubInt;
  FModelFactory.UpdateObserver('x', nil);

  Assert.IsTrue(FModelFactory.GetStubInt > ref, 'N�o chamou o evento do Observer');

  TMVCBr.UnRegisterObserver('x', FModelFactory);
end;

procedure TestTModelFactory.TestFreeInstanceLazyModel;

var LModel:IModelAdapter<TObjectComum>;
    LController:IController;
begin

    LModel := TModelAdapterFactory<TObjectComum>.new(LController);
    LModel.Instance.Execute(10);
    Assert.IsTrue(LModel.Instance.FCount=10,'N�o atribuiu valor');
    LModel := nil;


end;

procedure TestTModelFactory.TestThis;
var
  ReturnValue: TObject;
begin
  ReturnValue := FModelFactory.This;
  Assert.IsNotNull(ReturnValue, 'Nao retornou');
end;

procedure TestTModelFactory.TestGetID;
var
  ReturnValue: string;
begin
  ReturnValue := FModelFactory.GetID;
  Assert.IsTrue(ReturnValue <> '');
end;

procedure TestTModelFactory.TestID;
var
  ReturnValue: IModel;
  AID: string;
begin
  AID := 'teste.id';
  ReturnValue := FModelFactory.ID(AID);
  Assert.IsNotNull(ReturnValue, 'Nao retornou');
  Assert.AreEqual(AID, FModelFactory.GetID, 'ID should be set');
  ReturnValue := nil;
end;

procedure TestTModelFactory.TestRegisterObserver;
var
  ref, ref2: Integer;
begin
  ref := TMVCBrObservable.DefaultContainer.Count;
  TMVCBr.RegisterObserver('z', FModelFactory);
  ref2 := TMVCBrObservable.DefaultContainer.Count;
  Assert.IsTrue(ref2 > ref, 'Não incrementou a lista de observable');
  TMVCBr.UnRegisterObserver('z');
end;

procedure TestTModelFactory.TestUnRegisterObserverNamed;
begin
  TMVCBr.RegisterObserver('y', FModelFactory);
  TMVCBr.UnRegisterObserver('y', FModelFactory);

end;

procedure TestTModelFactory.TestUnRegisterObserverNamedOnly;
begin
  TMVCBr.RegisterObserver('k', FModelFactory);
  TMVCBr.UnRegisterObserver('k');

end;

procedure TestTModelFactory.TestUpdate;
var
  ReturnValue: IModel;
  refCount: Integer;
begin
  refCount := FModelFactory.GetStubInt;
  ReturnValue := FModelFactory.Update;
  Assert.IsNotNull(ReturnValue, 'Nao retornou');
  Assert.AreEqual(refCount + 1, FModelFactory.GetStubInt,
    'Update should increment counter');
end;

procedure TestTModelFactory.TestAfterInit;
begin
  FModelFactory.AfterInit;
  Assert.IsNotNull(FModelFactory.This);
end;

{ TModelFactoryMock }

{ TModelFactoryMock }

function TModelFactoryMock.GetStubInt: Integer;
begin
  result := FRefCount;
end;

function TModelFactoryMock.Update: IModel;
begin
  result := self;
  inc(FRefCount);
end;

{ TestTModuleModelFactory }

procedure TestTModuleModelFactory.SetUp;
begin
  FController := TTesteController.Create;
  FModelFactory := TModelAdapterFactory<TDataModuleMockTester>.new(FController);
  FController.add(FModelFactory);
end;

procedure TestTModuleModelFactory.TearDown;
begin
  FController.release;
  FController := nil;
end;


procedure TestTModuleModelFactory.TestGetController;
var
  ReturnValue: IController;
begin
  ReturnValue := FModelFactory.GetController;
  Assert.IsNotNull(ReturnValue, 'Nao retornou');
  if assigned(ReturnValue) then
    Assert.IsTrue(TMVCBr.IsSame(IController, TMVCBr.GetGuid(ReturnValue)));
  ReturnValue := nil;
end;


procedure TestTModuleModelFactory.TestLazyLoad;
var
  ReturnValue: IController;
begin
  ReturnValue := FModelFactory.GetController;
  Assert.IsNotNull(ReturnValue, 'Nao retornou');
  if assigned(ReturnValue) then
    Assert.IsTrue(TMVCBr.IsSame(IController, TMVCBr.GetGuid(ReturnValue)));
  Assert.IsTrue(FModelFactory.Instance.counter = 1, 'Nao executou Lazy Load');
  ReturnValue := nil;
end;


{ TObjectComum }

procedure TObjectComum.Execute(AValue:Integer);
begin
    FCount := AValue;
end;

end.
