unit TestMVCBr.Patterns.Lazy;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  DUnitX.TestFramework, System.SysUtils, System.Generics.Collections, System.JSON,
  System.RTTI, Forms,
  System.TypInfo, System.Classes,
  MVCBr.Interf, MVCBr.Patterns.States,
  MVCBr.Patterns.Lazy,
  MVCBr.Patterns.Decorator,
  MVCBr.Patterns.Strategy,
  MVCBr.BuilderModel,
  MVCBr.Factory, MVCBr.Patterns.Builder;

type

  [TestFixture]
  TLazyObject = class;

  TLazyObject = class
  public
    FCount: Integer;
    procedure Execute(AValue: Integer);
  end;

  TestTMVCBrLazyObject = class
  Private
    lzObject: TMVCBrLazyFactory<TObject>;

  public
    [Setup]
    procedure SetUp;
    [TearDown]
    procedure TearDown;
  public
    [Test]
    procedure TestCreateLazyObject;
    [Test]
    procedure TestLazyFactoryCreate;
    [Test]
    procedure TestAddCommand;
    [Test]
    procedure TestQueryCommand;
    [Test]
    procedure TestFreeInstance;
    [Test]
    procedure TestDelegate;
  end;



implementation



{ TestTMVCBrLazyObject }

procedure TestTMVCBrLazyObject.SetUp;
begin
  lzObject := TMVCBrLazyFactory<TObject>.Create;
end;

procedure TestTMVCBrLazyObject.TearDown;
begin
  lzObject.Free;
end;

procedure TestTMVCBrLazyObject.TestAddCommand;
begin
  lzObject.Add(1, TObject);
  lzObject.Add(2, TObject);
  Assert.IsTrue(lzObject.count = 2, 'N�o incluiu os itens');
end;

procedure TestTMVCBrLazyObject.TestCreateLazyObject;
var
  LLazy: IMVCBrLazy<TLazyObject>;
begin
  LLazy := TMVCBrLazy<TLazyObject>.Create(
    function: TLazyObject
    begin
      result := TLazyObject.Create;
    end);
  LLazy.Execute(10);
  Assert.IsTrue(LLazy.FCount = 10, 'N�o Executou o LazyObject');
end;

procedure TestTMVCBrLazyObject.TestDelegate;
begin
  lzObject.Add<TLazyObject>(1).DelegateTo(
    function: TLazyObject
    begin
      result := TLazyObject.Create;
    end).instance;

  Assert.IsTrue(lzObject.Query(1).IsCreated, 'N�o inicilizou');

  Assert.IsTrue(lzObject.Query(1).instance.InheritsFrom(TLazyObject),
    'N�o inicilizou TLazyObject');

end;

procedure TestTMVCBrLazyObject.TestFreeInstance;
begin
  lzObject.Add(1, TObject);
  Assert.IsTrue(lzObject.Query(1).IsCreated = false,
    'Inicializou a instance antes de chama-la');

  lzObject.Query(1).instance;
  Assert.IsTrue(lzObject.Query(1).IsCreated, 'N�o incializou a instancia');

end;

procedure TestTMVCBrLazyObject.TestLazyFactoryCreate;
begin
  lzObject.Add(1, TObject);
  Assert.IsTrue(lzObject.count > 0, 'N�o incluiu o item');
end;

procedure TestTMVCBrLazyObject.TestQueryCommand;
begin
  lzObject.Add(1, TObject);
  lzObject.Add(2, TComponent);
  lzObject.Add(3, TObject);

  Assert.IsTrue(lzObject.Query(2).instance.InheritsFrom(TComponent),
    'N�o achou o TComponent');

end;

{ TLazyObject }

procedure TLazyObject.Execute(AValue: Integer);
begin
  FCount := AValue;
end;

end.
