unit TestMVCBrInterf;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.Classes, System.RTTI, System.TypInfo,
  System.Generics.Collections, MVCBr.Interf, System.SysUtils;

type
  TestInterfs = class(TTestCase)
  published
    procedure TestGUID;
    procedure TestIsSameDiferentes;
    procedure TestIsSameIguais;
    procedure TestIsService;
  end;

implementation

{ TestInterfs }

type
  IInterfaceTeste = interface
    ['{35A547B7-E304-4E09-A99F-B7FAC2A60AD7}']
  end;

  IInterfaceTeste2 = interface
    ['{B0E7B1BE-BBC2-49F3-AFE5-F9F26E1BFBD3}']
  end;

  TObjectIntrf = class(TInterfacedObject, IInterfaceTeste)

  end;

  TObjectIntrf2 = class(TInterfacedObject, IInterfaceTeste2)

  end;

procedure TestInterfs.TestGUID;
var
  guid: TGuid;
  AInterface: IInterfaceTeste;
begin
  AInterface := TObjectIntrf.create;
  guid := TMVCBr.GetGuid(AInterface);
  checkTrue(TMVCBr.GetGuidString(guid) = TMVCBr.GetGuidString
    (TMVCBr.GetGuid<IInterfaceTeste>()), 'Guid não confere');

  checkFalse(TMVCBr.GetGuidString(guid) = TMVCBr.GetGuidString
    (TMVCBr.GetGuid<IInterfaceTeste2>()), 'Falou ao testas se os GUID são diferentes');

end;


procedure TestInterfs.TestIsSameDiferentes;
begin
    checkFalse( TMVCBr.IsSame(IInterfaceTeste,IInterfaceTeste2), 'As interface falhou ao testar se são diferentes');
end;

procedure TestInterfs.TestIsSameIguais;
begin
    checkTrue( TMVCBr.IsSame(IInterfaceTeste,IInterfaceTeste), 'As interface falhou ao testar se são iguasi');
end;

procedure TestInterfs.TestIsService;
var o:TObjectIntrf;
begin
    o:=TObjectIntrf.create;
    checkTrue( TMVCBr.IsService<IInterfaceTeste>(o),'Falou ao checar IsService Iguais');
    checkFalse( TMVCBr.IsService<IInterfaceTeste2>(o),'Falou ao checar IsService Diferentes');
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestInterfs.Suite);

end.
