unit TestMVCBr.Controller;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  DUnitX.TestFramework, System.SysUtils,
  System.Generics.Collections, System.TypInfo,
  MVCBr.Interf, MVCBr.Model, MVCBr.ApplicationController,
  System.RTTI, MVCBr.View, System.Classes,
  MVCBr.Controller;

type

  // Test methods for class TControllerFactory
  ITestModel1 = interface(IModel)
    ['{1972DCFC-4365-49DA-81AD-E92DD58690AD}']
  end;

  [TestFixture]
  TTestModel1 = class(TModelFactory, ITestModel1)
  public
    Constructor Create; override;
    Destructor Destroy; override;
  end;

  TTestModel2 = class(TTestModel1);

  TTestModel3 = class(TTestModel1);

  TTestView = class(TViewFactory)
  end;

  TestTControllerFactory = class
  private
    FControllerFactory: IController;
  public
    [Setup]
    procedure SetUp;
    [TearDown]
    procedure TearDown;
  public
    [Test]
    procedure TestID;
    [Test]
    procedure TestGetModelByID;
    [Test]
    procedure TestDoCommand;
    [Test]
    procedure TestGetModel;
    [Test]
    procedure TestGetModelByType;
    [Test]
    procedure TestInit;
    [Test]
    procedure TestBeforeInit;
    [Test]
    procedure TestAfterInit;
    [Test]
    procedure TestGetView;
    [Test]
    procedure TestView;
    [Test]
    procedure TestThis;
    [Test]
    procedure TestControllerAs;
    [Test]
    procedure TestAdd;
    [Test]
    procedure TestIndexOf;
    [Test]
    procedure TestIndexOfModelType;
    [Test]
    procedure TestDelete;
    [Test]
    procedure TestCount;
    [Test]
    procedure TestForEach;
    [Test]
    procedure TestForEachFunc;
    [Test]
    procedure TestUpdateAll;
    [Test]
    procedure TestUpdateByModel;
    [Test]
    procedure TestUpdateByView;
    [Test]
    procedure TestResolveController;
    [Test]
    procedure TestRevokeController;

    [Test]
    procedure TestApplicationControllerResolveController;
    [Test]
    procedure TestResolveControllerName;

    [Test]
    procedure TestRegisterObserver;
    [Test]
    procedure TestUnRegisterObserverNamed;
    [Test]
    procedure TestUnRegisterObserverNamedOnly;
    [Test]
    procedure TesteObserver;

  end;

implementation

uses Test.Controller, Test.Controller.Interf, TestSecond.Controller.Interf;

procedure TestTControllerFactory.SetUp;
begin
  FControllerFactory := TControllerFactory.Create;
  FControllerFactory.add(TMVCBr.InvokeCreate<ITestModel1>(TTestModel1)
    .ID('teste.model'));
  FControllerFactory.View( TTestView.Create   );
end;

procedure TestTControllerFactory.TearDown;
begin
  FControllerFactory.release;
  FControllerFactory := nil;
end;

procedure TestTControllerFactory.TestID;
var
  ReturnValue: IController;
  AID: string;
begin
  // TODO: Setup method call parameters
  AID := FControllerFactory.this.ClassName;
  ReturnValue := TControllerFactory(FControllerFactory.this).ID(AID);
  Assert.IsNotNull(ReturnValue, 'N�o incializou o IController');
  ReturnValue := nil;
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestGetModelByID;
var
  ReturnValue: IModel;
begin
  // TODO: Setup method call parameters
  ReturnValue := TControllerFactory(FControllerFactory.this).GetModelByID('Teste.Model');
  Assert.IsNotNull(ReturnValue);
  ReturnValue := nil;
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestDoCommand;
var
  ACommand: string;
begin
  // TODO: Setup method call parameters
  FControllerFactory.DoCommand(ACommand, []);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TesteObserver;
begin
  FControllerFactory.RegisterObserver('x', FControllerFactory.this);
  FControllerFactory.UpdateObserver('x', nil);
  FControllerFactory.UnRegisterObserver('x', FControllerFactory.this);
end;

procedure TestTControllerFactory.TestGetModel;
var
  ReturnValue: IModel;
  idx: Integer;
begin
  // TODO: Setup method call parameters
  idx := FControllerFactory.Count - 1;
  ReturnValue := FControllerFactory.GetModel(idx);
  Assert.IsNotNull(ReturnValue);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestGetModelByType;
var
  ReturnValue: IModel;
  AModelType: TModelType;
begin
  // TODO: Setup method call parameters
  AModelType := mtCommon;
  ReturnValue := FControllerFactory.GetModelByType(AModelType);
  Assert.IsNotNull(ReturnValue);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestInit;
begin
  FControllerFactory.Init;
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestRegisterObserver;
begin
  FControllerFactory.RegisterObserver(FControllerFactory.this);
end;

procedure TestTControllerFactory.TestResolveController;
var
  ctrl: ITestController;
begin
  ctrl := FControllerFactory.this.ResolveController<ITestController>;
  Assert.IsNotNull(ctrl, 'N�o inicializou o controller');
end;

procedure TestTControllerFactory.TestRevokeController;
var
  AController: ITestSecondController2;
  ARefCount: Integer;
begin
  ApplicationController.RevokeController(ITestSecondController2);
  AController := ApplicationController.ResolveController(ITestSecondController2)
    as ITestSecondController2;
  ARefCount := AController.this.RefCount;

  Assert.IsTrue(AController.GetStubInt = 0, 'Contador n�o foi incilizado com 1');
  AController.IncContador;
  Assert.IsTrue(AController.GetStubInt = 1, 'Contador n�o foi incrementado para 2');

  // AController := nil ; // mata o controller
  ApplicationController.RevokeController(ITestSecondController2);
  AController := ApplicationController.ResolveController(ITestSecondController2)
    as ITestSecondController2;

  Assert.IsTrue(AController.this.RefCount = ARefCount,
    'Contador de referencia n�o se manteve');

  ApplicationController.RevokeController(ITestSecondController2);
  Assert.IsTrue(AController.GetStubInt2 = 0, 'Instancia nao foi reinicializada');
  AController := nil; // mata o controller

end;

procedure TestTControllerFactory.TestBeforeInit;
begin
  FControllerFactory.BeforeInit;
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestAfterInit;
begin
  FControllerFactory.AfterInit;
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestApplicationControllerResolveController;
var
  ctrl: ITestController;
begin
  ctrl := ApplicationController.ResolveController(ITestController)
    as ITestController;
  Assert.IsNotNull(ctrl, 'n�o executou  resolvecontroller do application');
end;

procedure TestTControllerFactory.TestResolveControllerName;
var
  ctrl: ITestController;
begin
  ctrl := TControllerAbstract.resolve(TTestController.ClassName)
    as ITestController;
  Assert.IsNotNull(ctrl, 'n�o executou  resolvecontroller do application');
end;

procedure TestTControllerFactory.TestGetView;
var
  ReturnValue: IView;
begin
  ReturnValue := FControllerFactory.GetView;
  Assert.IsNotNull(ReturnValue);

  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestView;
var
  ReturnValue: IController;
  AView: IView;
begin
  // TODO: Setup method call parameters
  AView := FControllerFactory.GetView;
  Assert.IsNotNull(AView, 'A View n�o foi inicializa');
  ReturnValue := FControllerFactory.View(AView);
  Assert.IsNotNull(ReturnValue, 'N�o retornou a view');

  Assert.AreSame(ReturnValue, FControllerFactory.GetView.GetController,
    'Mudou o Controller, quando o esperado � que continuaria o mesmo');
  Assert.AreSame(AView, FControllerFactory.GetView,
    'Mudou a View, quando o esperado � que continuaria a mesma');

  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestThis;
var
  ReturnValue: TControllerAbstract;
begin
  ReturnValue := FControllerFactory.this;
  Assert.IsNotNull(ReturnValue);
  // TODO: Validate method results

  Assert.IsTrue(ReturnValue.this.InheritsFrom(TControllerFactory),
    'N�o herdou de TControllerFactory');

end;

procedure TestTControllerFactory.TestControllerAs;
var
  ReturnValue: TControllerFactory;
begin
  ReturnValue := TControllerFactory(FControllerFactory.this);
  Assert.IsNotNull(ReturnValue);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestAdd;
var
  ReturnValue: Integer;
  AModel: IModel;
begin
  // TODO: Setup method call parameters
  AModel := TTestModel2.New<IModel>(TTestModel2);
  ReturnValue := FControllerFactory.add(AModel);
  Assert.IsTrue(ReturnValue > 0);
  AModel := nil;
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestIndexOf;
var
  ReturnValue: Integer;
  AModel: IModel;
begin
  // TODO: Setup method call parameters
  AModel := FControllerFactory.GetModel(0);
  ReturnValue := FControllerFactory.IndexOf(AModel);
  Assert.IsTrue(ReturnValue = 0);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestIndexOfModelType;
var
  ReturnValue: Integer;
  AModelType: TModelType;
begin
  // TODO: Setup method call parameters
  AModelType := mtCommon;
  ReturnValue := FControllerFactory.IndexOfModelType(AModelType);
  Assert.IsTrue(ReturnValue >= 0);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestDelete;
var
  Index: Integer;
begin
  // TODO: Setup method call parameters
  Index := FControllerFactory.Count - 1;
  FControllerFactory.Delete(Index);
  Assert.IsTrue(Index = FControllerFactory.Count);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestCount;
var
  ReturnValue: Integer;
begin
  ReturnValue := FControllerFactory.Count;
  Assert.IsTrue(ReturnValue > 0);
  Assert.IsTrue(ReturnValue > 0);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestForEach;
var
  AProc: TProc<IModel>;
  rt: boolean;
begin
  rt := false;
  // TODO: Setup method call parameters
  AProc := procedure(Mdl: IModel)
    begin
      rt := true;
    end;
  FControllerFactory.ForEach(AProc);
  Assert.IsTrue(rt);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestForEachFunc;
var
  AProc: TProc<IModel>;
  rt: boolean;
begin
  rt := false;
  // TODO: Setup method call parameters
  AProc := procedure(Mdl: IModel)
    begin
      rt := true;
    end;
  FControllerFactory.ForEach(AProc);
  Assert.IsTrue(rt);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestUnRegisterObserverNamed;
begin
  FControllerFactory.RegisterObserver('x', FControllerFactory.this);

end;

procedure TestTControllerFactory.TestUnRegisterObserverNamedOnly;
begin
  FControllerFactory.RegisterObserver('testname', FControllerFactory.this);
  FControllerFactory.UnRegisterObserver('testname');
end;

procedure TestTControllerFactory.TestUpdateAll;
var
  ReturnValue: IController;
begin
  ReturnValue := FControllerFactory.UpdateAll;
  Assert.IsNotNull(ReturnValue);
  // TODO: Validate method results
end;

procedure TestTControllerFactory.TestUpdateByModel;
var
  ReturnValue: IController;
  AModel: IModel;
begin
  // TODO: Setup method call parameters

  ReturnValue := FControllerFactory.UpdateByModel(AModel);
  // TODO: Validate method results
  Assert.IsNotNull(ReturnValue);
end;

procedure TestTControllerFactory.TestUpdateByView;
var
  ReturnValue: IController;
  AView: IView;
begin
  // TODO: Setup method call parameters
  AView := FControllerFactory.GetView;
  ReturnValue := FControllerFactory.UpdateByView(AView);
  Assert.IsNotNull(ReturnValue);
  // TODO: Validate method results
end;

{ TTestControllerFactory }

{ TTestModel }

constructor TTestModel1.Create;
begin

end;

destructor TTestModel1.Destroy;
begin

end;

end.
