/******************************************************************************/
/*           Generated by IBExpert 2017.1.25.1 20/03/2017 00:01:46            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE '127.0.0.1:c:\git\mvcbr\dados\mvcbr.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CLIENTES (
    CODIGO    INTEGER,
    NOME      VARCHAR(128),
    ENDERECO  VARCHAR(128),
    CIDADE    VARCHAR(50),
    ESTADO    VARCHAR(50)
);


CREATE TABLE FORNECEDORES (
    CODIGO  INTEGER,
    NOME    VARCHAR(128)
);


CREATE TABLE GRUPOS (
    CODIGO  VARCHAR(10) NOT NULL,
    NOME    VARCHAR(128)
);


CREATE TABLE PRODUTOS (
    CODIGO     VARCHAR(30),
    DESCRICAO  VARCHAR(128),
    GRUPO      VARCHAR(10),
    UNIDADE    VARCHAR(5),
    PRECO      DOUBLE PRECISION
);


CREATE TABLE VENDAS (
    DATA       DATE NOT NULL,
    DOCUMENTO  INTEGER NOT NULL,
    CLIENTE    INTEGER,
    TOTAL      DOUBLE PRECISION
);


CREATE TABLE VENDAS_ITEM (
    DATA             DATE NOT NULL,
    DOCUMENTO        INTEGER NOT NULL,
    PRODUTOS_CODIGO  VARCHAR(30),
    QTDE             DOUBLE PRECISION,
    PRECO            DOUBLE PRECISION,
    VALOR            DOUBLE PRECISION
);




/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE GRUPOS ADD CONSTRAINT PK_GRUPOS PRIMARY KEY (CODIGO);
ALTER TABLE VENDAS ADD CONSTRAINT PK_VENDAS PRIMARY KEY (DATA, DOCUMENTO);
ALTER TABLE VENDAS_ITEM ADD CONSTRAINT PK_VENDAS_ITEM PRIMARY KEY (DATA, DOCUMENTO);


/******************************************************************************/
/*                                  Indices                                   */
/******************************************************************************/

CREATE INDEX GRUPOS_IDX1 ON GRUPOS (NOME);
