const
  wizardProjectExpertCaption = 'MVCBr Project';
  wizardForm_all = 'All';

  wizardForm_label_caption = 'Building ApplicationController';
  wizardForm_caption = 'Project Expert - MVCBr';
  wizardForm_label_ident = 'Project name';
  wizardForm_label_folder = 'Project home path';
  wizardForm_button_search = 'Search';
  wizardForm_createdir_checkbox_caption = 'keep artefact in the home folder';
  wizardForm_groupdir_checkbox_caption = 'keep artefact in the same folder';
  wizardForm_NameFor = 'Name for %s';
  wizardForm_NameForArtefact = 'Artefact name';

  wizardForm_ViewModel_Expert = 'Expert for View/ViewModel or Model';
  wizardForm_checkBox_createmodel_caption = 'Create Model';
  wizardForm_checkBox_createview_caption = 'Create View';
  wizardForm_checkBox_createviewmodel_caption = 'Create ViewModel';
  wizarForm_createview_tipoview_caption = 'Choose View inherits from';

  wizardForm_module_title_caption = 'Module Model Expert';
  wizardMuduleFactoryCreate_caption = 'Create Model';

  button_back_caption = 'Back';
  button_cancel_caption = 'Cancel';
  button_finish_caption = 'Finish';
  button_next_caption = 'Next';

  msgDontFindCreateProjectBefore =
    'Project MVCBr dont exists, create a project before!';
  msgSorryFileExists = 'Sorry, there is a file "%s" with the same name!';
  msgNeedNameFor = '%s must have a name.';
  msgGiveClassFor = 'Please give select or input a parent class for the %s.';

  msgCongratulation = 'Congratulation';

  wizardPersistentModel_Expert_Caption = 'Models Expert';
  wizardPersistentCreateModelFactory_caption = 'Create model artefact';

  wizardController_Expert_Caption = 'Create controller artefact';
  wizardController_CreateModel_caption = 'Create Model';

  wizardClassModel_Caption = 'Class Model Importer';
  wizardClassModel_Import_caption = 'Class importer';
  wizardClassModel_expert_caption = 'Class model importer expert';
  wizardClassModel_label_unitbase = 'Base Unit to import class';

  wizardClassModel_label_classbase = 'Base class to import';
  wizardImportClass_MakeFunc_caption = 'Create Interface to';

  wizardImportClass_label_modelname = 'New Model Artefact name';
