const
  wizardProjectExpertCaption = 'Projeto MVCBr';
  wizardForm_all = 'Todos';

  wizardForm_label_caption = 'Gerar um ApplicationController';
  wizardForm_caption = 'Assitente para o Projeto MVCBr';
  wizardForm_label_ident = 'Nome identificador para o projeto';
  wizardForm_label_folder = 'Pasta para o projeto';
  wizardForm_button_search = 'Localizar';
  wizardForm_createdir_checkbox_caption = 'manter os artefatos na raiz';

  wizardForm_NameFor = 'Nome identificador para %s';
  wizardForm_NameForArtefact = 'Nome para o artefato';

  wizardForm_ViewModel_Expert = 'Assistente para View/ViewModel ou Model';
  wizardForm_checkBox_createmodel_caption = 'Criar Model';
  wizardForm_checkBox_createview_caption = 'Criar View';
  wizardForm_checkBox_createviewmodel_caption = 'Criar ViewModel';
  wizarForm_createview_tipoview_caption = 'Selecione a herança da view';

  wizardForm_module_title_caption = 'Assistente para DataModule Factory';
  wizardMuduleFactoryCreate_caption = 'Criar Model';

  button_back_caption = 'Voltar';
  button_cancel_caption = 'Cancelar';
  button_finish_caption = 'Finalizar';
  button_next_caption = 'Próximo';

  msgDontFindCreateProjectBefore =
    'Não encontrei o projeto MVCBr, criar um projeto antes!';
  msgSorryFileExists = 'Desculpe, tem um arquivo "%s" com o mesmo nome!';
  msgNeedNameFor = 'Indicar o nome para %s.';
  msgGiveClassFor = 'Fornecer uma classe de herança para %s.';
  msgCongratulation = 'Parabens';

  wizardPersistentModel_Expert_Caption = 'Assistente para criar Models';
  wizardPersistentCreateModelFactory_caption = 'Criar model factory';

  wizardController_Expert_Caption = 'Criar controller factory';
  wizardController_CreateModel_caption = 'Criar Model';

  wizardClassModel_Import_caption = 'Importar classe';
  wizardImportClass_MakeFunc_caption = 'Criar interface para';
  wizardClassModel_expert_caption =
    'Assistente para gerar model para uma classe';

  wizardClassModel_Caption = 'Importar classe';
  wizardClassModel_label_unitbase = 'Unit base para extrair as classes';
  wizardClassModel_label_classbase = 'Class base para extrair o módulo';
  wizardImportClass_label_modelname = 'Nome indenficador para a Classe BASE';
