DatasetModelIntef = 'Unit %ModelIdent '+CR+
'                                                                       '+CR+
'Interface                                                              '+CR+
'                                                                       '+CR+
'Uses System.Classes, MVCBr.Model,MVCBr.PersistentModel;                '+CR+
'                                                                       '+CR+
'Implementation                                                         '+CR+
'                                                                       '+CR+
'                                                                       '+CR+
'                                                                       '+CR+
'                                                                       '+CR+
'end.                                                                   ';


DatasetModel = 'Unit %ModelIdent '+CR+
'                                                                       '+CR+
'Interface                                                              '+CR+
'                                                                       '+CR+
'Uses System.Classes, MVCBr.Model,MVCBr.PersistentModel;                '+CR+
'                                                                       '+CR+
'Implementation                                                         '+CR+
'                                                                       '+CR+
'                                                                       '+CR+
'                                                                       '+CR+
'                                                                       '+CR+
'end.';
