DatasetModelIntef = 'Unit %UnitIdent '+#13#10+
'                                                                       '+#13#10+
'Interface                                                              '+#13#10+
'                                                                       '+#13#10+
'Uses System.Classes, MVCBr.Model,MVCBr.PersistentModel;                '+#13#10+
'                                                                       '+#13#10+
'Implementation                                                         '+#13#10+
'                                                                       '+#13#10+
'                                                                       '+#13#10+
'                                                                       '+#13#10+
'                                                                       '+#13#10+
'end.                                                                   ';


DatasetModel = 'Unit %UnitIdent '+#13#10+
'                                                                       '+#13#10+
'Interface                                                              '+#13#10+
'                                                                       '+#13#10+
'Uses System.Classes, MVCBr.Model,MVCBr.PersistentModel;                '+#13#10+
'                                                                       '+#13#10+
'Implementation                                                         '+#13#10+
'                                                                       '+#13#10+
'                                                                       '+#13#10+
'                                                                       '+#13#10+
'                                                                       '+#13#10+
'end.';
